#if defined __ph_propdata_included
	#endinput
#endif
#define __ph_propdata_included

// Global prop rules (addons/sourcemod/configs/prophunt/props.cfg): exact-model overrides,
// then regex patterns (both may blacklist a model or nudge its Z offset), first match wins.
static StringMap g_hModelOverrides = null;			// model(lower) -> [0]=blacklist float(0/1) [1..3]=offset
static ArrayList g_hPatternRegex = null;			// Handle (Regex)
static ArrayList g_hPatternBlacklist = null;		// int (0/1)
static ArrayList g_hPatternOffset = null;			// float[3]

// Per-map static/dynamic/physics prop dump, generated by tools/prophunt_propscan.py.
static ArrayList g_hMapPropModel = null;			// String[PLATFORM_MAX_PATH]
static ArrayList g_hMapPropOrigin = null;			// float[3]
static ArrayList g_hMapPropAngles = null;			// float[3]
static ArrayList g_hMapPropType = null;			// int (PHPropType)

// Model -> bounding-box diagonal length cache, filled lazily the first time a model is
// actually considered (spawning a scratch entity for every one of tens of thousands of
// props at map start would be wasteful; most are never aimed at in a given round).
static StringMap g_hModelBoundsCache = null;

#define PH_MAX_MAP_PROPS 20000

void PH_PropData_Init()
{
	PH_PropData_LoadGlobalRules();
}

void PH_PropData_OnMapStart()
{
	delete g_hMapPropModel;
	delete g_hMapPropOrigin;
	delete g_hMapPropAngles;
	delete g_hMapPropType;
	delete g_hModelBoundsCache;

	g_hMapPropModel = new ArrayList(ByteCountToCells(PLATFORM_MAX_PATH));
	g_hMapPropOrigin = new ArrayList(3);
	g_hMapPropAngles = new ArrayList(3);
	g_hMapPropType = new ArrayList(1);
	g_hModelBoundsCache = new StringMap();

	PH_PropData_LoadMapFile();
}

void PH_PropData_LoadGlobalRules()
{
	delete g_hModelOverrides;
	delete g_hPatternRegex;
	delete g_hPatternBlacklist;
	delete g_hPatternOffset;

	g_hModelOverrides = new StringMap();
	g_hPatternRegex = new ArrayList();
	g_hPatternBlacklist = new ArrayList();
	g_hPatternOffset = new ArrayList(3);

	char path[PLATFORM_MAX_PATH];
	BuildPath(Path_SM, path, sizeof(path), "configs/prophunt/props.cfg");

	KeyValues kv = new KeyValues("PropHuntProps");
	if (!kv.ImportFromFile(path))
	{
		LogError("[PropHunt] Could not load %s - all props will be allowed subject to size limits only.", path);
		delete kv;
		return;
	}

	if (kv.JumpToKey("Models") && kv.GotoFirstSubKey(false))
	{
		char model[PLATFORM_MAX_PATH], lower[PLATFORM_MAX_PATH];
		do
		{
			kv.GetSectionName(model, sizeof(model));
			if (model[0] == '\0')
				continue;

			strcopy(lower, sizeof(lower), model);
			PH_StrToLowerInPlace(lower);

			float entry[4];
			entry[0] = kv.GetNum("blacklist", 0) ? 1.0 : 0.0;

			char offsetStr[64];
			float tmpOffset[3];
			kv.GetString("offset", offsetStr, sizeof(offsetStr), "0 0 0");
			PH_ParseVector(offsetStr, tmpOffset);
			entry[1] = tmpOffset[0];
			entry[2] = tmpOffset[1];
			entry[3] = tmpOffset[2];

			g_hModelOverrides.SetArray(lower, entry, sizeof(entry));
		}
		while (kv.GotoNextKey(false));
		kv.GoBack();
	}
	kv.GoBack();

	if (kv.JumpToKey("Patterns") && kv.GotoFirstSubKey(false))
	{
		char pattern[256], errBuf[128];
		RegexError errCode;
		do
		{
			kv.GetString("pattern", pattern, sizeof(pattern), "");
			if (pattern[0] == '\0')
				continue;

			Regex rx = new Regex(pattern, PCRE_CASELESS, errBuf, sizeof(errBuf), errCode);
			if (rx == null)
			{
				char name[128];
				kv.GetSectionName(name, sizeof(name));
				LogError("[PropHunt] props.cfg pattern '%s' failed to compile: %s", name, errBuf);
				continue;
			}

			int blacklist = kv.GetNum("blacklist", 0);

			float offset[3];
			char offsetStr[64];
			kv.GetString("offset", offsetStr, sizeof(offsetStr), "0 0 0");
			PH_ParseVector(offsetStr, offset);

			g_hPatternRegex.Push(rx);
			g_hPatternBlacklist.Push(blacklist);
			g_hPatternOffset.PushArray(offset, 3);
		}
		while (kv.GotoNextKey(false));
		kv.GoBack();
	}

	delete kv;
}

void PH_PropData_LoadMapFile()
{
	char map[128], path[PLATFORM_MAX_PATH];
	GetCurrentMap(map, sizeof(map));
	BuildPath(Path_SM, path, sizeof(path), "configs/prophunt/maps/%s.cfg", map);

	if (!FileExists(path))
	{
		LogError("[PropHunt] No prop data file for map '%s' (expected %s). Static-prop disguises will be unavailable; \
run tools/prophunt_propscan.py to generate it. Live entity disguises still work.", map, path);
		return;
	}

	File file = OpenFile(path, "r");
	if (file == null)
	{
		LogError("[PropHunt] Failed to open prop data file %s", path);
		return;
	}

	char line[PLATFORM_MAX_PATH + 96];
	char parts[4][PLATFORM_MAX_PATH];
	int loaded = 0;

	while (!file.EndOfFile() && file.ReadLine(line, sizeof(line)) && loaded < PH_MAX_MAP_PROPS)
	{
		int len = strlen(line);
		while (len > 0 && (line[len - 1] == '\n' || line[len - 1] == '\r'))
			line[--len] = '\0';

		if (line[0] == '\0' || (line[0] == '/' && line[1] == '/'))
			continue;

		if (ExplodeString(line, "|", parts, sizeof(parts), sizeof(parts[])) != 4)
			continue;

		PHPropType type;
		if (StrEqual(parts[0], "static"))
			type = PHProp_Static;
		else if (StrEqual(parts[0], "dynamic"))
			type = PHProp_Dynamic;
		else if (StrEqual(parts[0], "physics"))
			type = PHProp_Physics;
		else
			continue;

		float origin[3], angles[3];
		if (!PH_ParseVector(parts[2], origin) || !PH_ParseVector(parts[3], angles))
			continue;

		g_hMapPropModel.PushString(parts[1]);
		g_hMapPropOrigin.PushArray(origin, 3);
		g_hMapPropAngles.PushArray(angles, 3);
		g_hMapPropType.Push(type);
		loaded++;
	}

	delete file;

	LogMessage("[PropHunt] Loaded %d static/dynamic/physics props for map '%s'.", loaded, map);
}

// ------------------------------------------------------------------------------------------

stock bool PH_ParseVector(const char[] text, float vec[3])
{
	char parts[3][32];
	if (ExplodeString(text, " ", parts, 3, sizeof(parts[])) != 3)
		return false;

	vec[0] = StringToFloat(parts[0]);
	vec[1] = StringToFloat(parts[1]);
	vec[2] = StringToFloat(parts[2]);
	return true;
}

stock void PH_StrToLowerInPlace(char[] text)
{
	int len = strlen(text);
	for (int i = 0; i < len; i++)
		text[i] = CharToLower(text[i]);
}

// Returns false if the model is blacklisted by props.cfg. When allowed, offset is filled
// with the Z-nudge (and any XY nudge) that should be applied to the visual prop.
bool PH_IsModelAllowed(const char[] model, float offset[3])
{
	offset[0] = 0.0;
	offset[1] = 0.0;
	offset[2] = 0.0;

	char lower[PLATFORM_MAX_PATH];
	strcopy(lower, sizeof(lower), model);
	PH_StrToLowerInPlace(lower);

	if (g_hModelOverrides != null)
	{
		float entry[4];
		if (g_hModelOverrides.GetArray(lower, entry, sizeof(entry)))
		{
			offset[0] = entry[1];
			offset[1] = entry[2];
			offset[2] = entry[3];
			return entry[0] < 0.5;
		}
	}

	if (g_hPatternRegex != null)
	{
		int count = g_hPatternRegex.Length;
		for (int i = 0; i < count; i++)
		{
			Regex rx = view_as<Regex>(g_hPatternRegex.Get(i));
			if (rx.Match(lower) > 0)
			{
				float patOffset[3];
				g_hPatternOffset.GetArray(i, patOffset, 3);
				offset[0] = patOffset[0];
				offset[1] = patOffset[1];
				offset[2] = patOffset[2];
				return g_hPatternBlacklist.Get(i) == 0;
			}
		}
	}

	return true;
}

bool PH_IsSizeAllowed(float diagonal)
{
	if (g_flCvarPropMinSize > 0.0 && diagonal < g_flCvarPropMinSize)
		return false;
	if (g_flCvarPropMaxSize > 0.0 && diagonal > g_flCvarPropMaxSize)
		return false;
	return true;
}

// Bounding-box diagonal length for a model, used both for the size-limit check and as the
// hit-test radius (half the diagonal) when a static prop has no live entity to trace against.
// Cached per-model since spawning a scratch entity has a real (if small) cost.
bool PH_GetModelBoundsDiagonal(const char[] model, float &diagonal)
{
	char lower[PLATFORM_MAX_PATH];
	strcopy(lower, sizeof(lower), model);
	PH_StrToLowerInPlace(lower);

	if (g_hModelBoundsCache != null && g_hModelBoundsCache.GetValue(lower, diagonal))
		return true;

	if (!PrecacheModel(model, true))
	{
		diagonal = 0.0;
		return false;
	}

	int scratch = CreateEntityByName("prop_dynamic_override");
	if (scratch == -1)
		scratch = CreateEntityByName("prop_dynamic");

	if (scratch == -1)
	{
		diagonal = 0.0;
		return false;
	}

	SetEntityModel(scratch, model);
	SetEntProp(scratch, Prop_Send, "m_CollisionGroup", 1); // COLLISION_GROUP_DEBRIS
	SetEntProp(scratch, Prop_Send, "m_nSolidType", 0); // SOLID_NONE
	SetEntityRenderMode(scratch, RENDER_NONE);
	TeleportEntity(scratch, view_as<float>({0.0, 0.0, -8192.0}), NULL_VECTOR, NULL_VECTOR);
	DispatchSpawn(scratch);

	float mins[3], maxs[3];
	GetEntPropVector(scratch, Prop_Send, "m_vecMins", mins);
	GetEntPropVector(scratch, Prop_Send, "m_vecMaxs", maxs);
	diagonal = GetVectorDistance(mins, maxs);

	if (IsValidEntity(scratch))
		AcceptEntityInput(scratch, "Kill");

	if (diagonal <= 0.1)
		diagonal = 32.0; // Model reported no bounds (rare) - assume a small generic prop.

	if (g_hModelBoundsCache != null)
		g_hModelBoundsCache.SetValue(lower, diagonal);

	return true;
}

int PH_PropData_Count()
{
	return (g_hMapPropModel != null) ? g_hMapPropModel.Length : 0;
}

void PH_PropData_Get(int index, char model[PLATFORM_MAX_PATH], float origin[3], float angles[3], PHPropType &type)
{
	g_hMapPropModel.GetString(index, model, PLATFORM_MAX_PATH);
	g_hMapPropOrigin.GetArray(index, origin, 3);
	g_hMapPropAngles.GetArray(index, angles, 3);
	type = view_as<PHPropType>(g_hMapPropType.Get(index));
}
