#!/usr/bin/env python3
"""
Prop Hunt map prop scanner.

Parses the decompiled VMF files in "decompiled maps/" and extracts every
prop_static / prop_dynamic(_override) / prop_physics(_override) entity's
model, origin and angles, writing one flat data file per map to
addons/sourcemod/configs/prophunt/maps/<mapname>.cfg.

These per-map files are read at runtime by the kether_prophunt plugin
(scripting/kether/prophunt/propdata.sp) to let a disguised prop-hunt player
select any static prop in the map with +use, not just spawned entities.

Usage:
    python3 tools/prophunt_propscan.py
    python3 tools/prophunt_propscan.py --maps c1m1_hotel,c2m1_highway
    python3 tools/prophunt_propscan.py --input-dir "decompiled maps" --output-dir addons/sourcemod/configs/prophunt/maps
"""

import argparse
import os
import re
import sys

KV_LINE = re.compile(r'^"((?:[^"\\]|\\.)*)"\s+"((?:[^"\\]|\\.)*)"\s*$')

# classname -> disguise type tag written to the output file
PROP_CLASSES = {
    "prop_static": "static",
    "prop_dynamic": "dynamic",
    "prop_dynamic_override": "dynamic",
    "prop_physics": "physics",
    "prop_physics_override": "physics",
    "prop_physics_multiplayer": "physics",
}

# Models that are never worth disguising as (empty/placeholder/broken refs).
MODEL_BLACKLIST_SUBSTR = (
    "error.mdl",
    "hidden.mdl",
)


def parse_vmf_entities(path):
    """Yields dicts of key->value for every top-level 'entity { ... }' block."""
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        lines = f.readlines()

    i = 0
    n = len(lines)
    while i < n:
        if lines[i].strip() == "entity":
            # Expect the opening brace on one of the next couple of lines.
            j = i + 1
            while j < n and lines[j].strip() == "":
                j += 1
            if j >= n or lines[j].strip() != "{":
                i += 1
                continue

            depth = 1
            j += 1
            entity = {}
            while j < n and depth > 0:
                stripped = lines[j].strip()
                if stripped == "{":
                    depth += 1
                elif stripped == "}":
                    depth -= 1
                elif depth == 1:
                    m = KV_LINE.match(stripped)
                    if m:
                        key, value = m.group(1), m.group(2)
                        # Keep the first occurrence; VMF entities shouldn't
                        # repeat keys, but be defensive.
                        entity.setdefault(key.lower(), value)
                j += 1

            if entity:
                yield entity
            i = j
        else:
            i += 1


def is_usable_model(model):
    if not model:
        return False
    low = model.lower()
    if not low.endswith(".mdl"):
        return False
    for bad in MODEL_BLACKLIST_SUBSTR:
        if bad in low:
            return False
    return True


def normalize_vec(text, default="0 0 0"):
    if not text:
        text = default
    parts = text.replace(",", " ").split()
    if len(parts) != 3:
        return default
    try:
        return " ".join("%g" % float(p) for p in parts)
    except ValueError:
        return default


def scan_map(vmf_path):
    """Returns a list of (type, model, origin, angles) tuples, deduplicated."""
    seen = set()
    results = []

    for entity in parse_vmf_entities(vmf_path):
        classname = entity.get("classname", "")
        prop_type = PROP_CLASSES.get(classname)
        if prop_type is None:
            continue

        model = entity.get("model", "")
        if not is_usable_model(model):
            continue

        # Props parented to another entity (elevators, moving machinery,
        # animated fixtures) report their origin relative to the parent,
        # not world space - not safe to use as a static disguise spot.
        if entity.get("parentname"):
            continue

        model = model.replace("\\", "/")
        origin = normalize_vec(entity.get("origin"))
        angles = normalize_vec(entity.get("angles"))

        key = (prop_type, model, origin, angles)
        if key in seen:
            continue
        seen.add(key)
        results.append(key)

    return results


def map_name_from_filename(filename):
    base = os.path.splitext(os.path.basename(filename))[0]
    if base.endswith("_d"):
        base = base[:-2]
    return base


def write_map_file(output_path, map_name, props):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/prophunt_propscan.py - do not edit by hand.\n")
        f.write("// Regenerate with: python3 tools/prophunt_propscan.py --maps %s\n" % map_name)
        f.write("// map=%s count=%d\n" % (map_name, len(props)))
        f.write("// type|model|ox oy oz|ax ay az\n")
        for prop_type, model, origin, angles in props:
            f.write("%s|%s|%s|%s\n" % (prop_type, model, origin, angles))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--input-dir",
        default=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "decompiled maps"),
        help="Directory containing the decompiled *_d.vmf files.",
    )
    parser.add_argument(
        "--output-dir",
        default=os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "addons", "sourcemod", "configs", "prophunt", "maps",
        ),
        help="Directory to write <mapname>.cfg prop data files to.",
    )
    parser.add_argument(
        "--maps",
        default=None,
        help="Comma-separated list of map names (without _d.vmf) to scan. Default: all.",
    )
    parser.add_argument(
        "--min-count",
        type=int,
        default=1,
        help="Skip writing a map file if fewer than this many usable props were found.",
    )
    args = parser.parse_args()

    if not os.path.isdir(args.input_dir):
        print("Input directory not found: %s" % args.input_dir, file=sys.stderr)
        return 1

    wanted = None
    if args.maps:
        wanted = {m.strip() for m in args.maps.split(",") if m.strip()}

    vmf_files = sorted(
        f for f in os.listdir(args.input_dir)
        if f.lower().endswith(".vmf")
    )

    total_props = 0
    written = 0
    for filename in vmf_files:
        map_name = map_name_from_filename(filename)
        if wanted is not None and map_name not in wanted:
            continue

        vmf_path = os.path.join(args.input_dir, filename)
        props = scan_map(vmf_path)

        if len(props) < args.min_count:
            print("Skipping %-28s (%d usable props, below --min-count)" % (map_name, len(props)))
            continue

        output_path = os.path.join(args.output_dir, "%s.cfg" % map_name)
        write_map_file(output_path, map_name, props)
        print("Wrote %-28s -> %-4d props -> %s" % (map_name, len(props), output_path))
        total_props += len(props)
        written += 1

    print("\nDone: %d map files written, %d total props." % (written, total_props))
    return 0


if __name__ == "__main__":
    sys.exit(main())
